exclude: ^(scripts|comictaggerlib/graphics/resources.py)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v3.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
    -   id: autoflake
        args: [-i, --remove-all-unused-imports, --ignore-init-module-imports]
-   repo: https://github.com/PyCQA/isort
    rev: 9.0.0b2
    hooks:
    -   id: isort
        args: [--af,--add-import, 'from __future__ import annotations']
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-encodings, flake8-builtins, flake8-print, flake8-no-nested-comprehensions, flake8-logging]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-setuptools, types-requests, settngs>=0.10.4, pillow>=9.1.0]
ci:
    skip: [mypy]
